-- DELETE FROM "Lesson" *;

-- TRUNCATE TABLE "Lesson" RESTART IDENTITY;

INSERT INTO "Lesson" VALUES
( DEFAULT, 'Математика', False, 85 ),
( DEFAULT, 'Математика', True, 84 ),
( DEFAULT, 'Физика', False, 47 ),
( DEFAULT, 'Физика', True, 23 ),
( DEFAULT, 'Химия', False, 37 ),
( DEFAULT, 'Химия', True, 66 ),
( DEFAULT, 'Биология', False, 54 ),
( DEFAULT, 'Биология', True, 115 ),
( DEFAULT, 'Информатика', False, 49 ),
( DEFAULT, 'Информатика', True, 36 ),
( DEFAULT, 'Программирование', False, 99 ),
( DEFAULT, 'Программирование', True, 104 ),
( DEFAULT, 'Экономика', False, 47 ),
( DEFAULT, 'Экономика', True, 72 ),
( DEFAULT, 'Менеджмент', False, 51 ),
( DEFAULT, 'Менеджмент', True, 53 ),
( DEFAULT, 'Финансы', False, 116 ),
( DEFAULT, 'Финансы', True, 111 ),
( DEFAULT, 'Маркетинг', False, 93 ),
( DEFAULT, 'Маркетинг', True, 118 ),
( DEFAULT, 'Психология', False, 121 ),
( DEFAULT, 'Психология', True, 91 ),
( DEFAULT, 'Социология', False, 53 ),
( DEFAULT, 'Социология', True, 88 ),
( DEFAULT, 'Философия', False, 83 ),
( DEFAULT, 'Философия', True, 114 ),
( DEFAULT, 'История', False, 33 ),
( DEFAULT, 'История', True, 113 ),
( DEFAULT, 'Политология', False, 125 ),
( DEFAULT, 'Политология', True, 26 ),
( DEFAULT, 'Право', False, 110 ),
( DEFAULT, 'Право', True, 85 ),
( DEFAULT, 'Лингвистика', False, 28 ),
( DEFAULT, 'Лингвистика', True, 104 ),
( DEFAULT, 'Литературоведение', False, 114 ),
( DEFAULT, 'Литературоведение', True, 26 ),
( DEFAULT, 'Иностранный язык', False, 27 ),
( DEFAULT, 'Иностранный язык', True, 120 ),
( DEFAULT, 'Физическая культура', False, 38 ),
( DEFAULT, 'Физическая культура', True, 42 ),
( DEFAULT, 'География', False, 125 ),
( DEFAULT, 'География', True, 22 ),
( DEFAULT, 'Геология', False, 111 ),
( DEFAULT, 'Геология', True, 35 ),
( DEFAULT, 'Астрономия', False, 125 ),
( DEFAULT, 'Астрономия', True, 101 ),
( DEFAULT, 'Архитектура', False, 85 ),
( DEFAULT, 'Архитектура', True, 62 ),
( DEFAULT, 'Дизайн', False, 16 ),
( DEFAULT, 'Дизайн', True, 75 ),
( DEFAULT, 'Искусство', False, 77 ),
( DEFAULT, 'Искусство', True, 71 ),
( DEFAULT, 'Музыка', False, 69 ),
( DEFAULT, 'Музыка', True, 105 ),
( DEFAULT, 'Театр', False, 86 ),
( DEFAULT, 'Театр', True, 80 ),
( DEFAULT, 'Кино', False, 55 ),
( DEFAULT, 'Кино', True, 28 ),
( DEFAULT, 'Спорт', False, 59 ),
( DEFAULT, 'Спорт', True, 42 ),
( DEFAULT, 'Биохимия', False, 67 ),
( DEFAULT, 'Биохимия', True, 30 ),
( DEFAULT, 'Генетика', False, 68 ),
( DEFAULT, 'Генетика', True, 74 ),
( DEFAULT, 'Микробиология', False, 88 ),
( DEFAULT, 'Микробиология', True, 20 ),
( DEFAULT, 'Медицина', False, 49 ),
( DEFAULT, 'Медицина', True, 41 ),
( DEFAULT, 'Педагогика', False, 99 ),
( DEFAULT, 'Педагогика', True, 81 ),
( DEFAULT, 'Психология развития', False, 121 ),
( DEFAULT, 'Психология развития', True, 107 ),
( DEFAULT, 'Социальная работа', False, 17 ),
( DEFAULT, 'Социальная работа', True, 90 ),
( DEFAULT, 'Туризм', False, 61 ),
( DEFAULT, 'Туризм', True, 84 ),
( DEFAULT, 'Гостиничный бизнес', False, 64 ),
( DEFAULT, 'Гостиничный бизнес', True, 112 ),
( DEFAULT, 'Журналистика', False, 122 ),
( DEFAULT, 'Журналистика', True, 52 ),
( DEFAULT, 'Реклама', False, 117 ),
( DEFAULT, 'Реклама', True, 105 ),
( DEFAULT, 'Связи с общественностью', False, 27 ),
( DEFAULT, 'Связи с общественностью', True, 81 );

SELECT * FROM "Lesson"